database:
  user: "sa_user"
  password: "omEYxipkmbhFJYg9LcZ9"  
  host: "mysql" 
  port: 3306
  name: "singularity_academy"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

email:
  email: admin@dicloud.vip
  password: 6kziffhAngtWsJas
  host: smtp.exmail.qq.com
  port: 465
