[project]
name = "singulariyacademy"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "aiomysql>=0.2.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.29",
    "langchain-openai>=0.3.33",
    "loguru>=0.7.3",
    "manim>=0.19.0",
    "openai>=1.107.2",
    "pydantic>=2.11.9",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "sanic>=25.3.0",
    "sanic-cors>=2.2.0",
    "tortoise-orm>=0.25.1",
    "ujson>=5.11.0",
]
