from tortoise import fields, models
from tortoise.contrib.sanic import register_tortoise
from tortoise.transactions import in_transaction
import yaml
import json as py_json # Renamed to avoid conflict with sanic.json if used in same context elsewhere
from datetime import datetime, timezone
import os
import logging # For logging validation errors or method actions
import uuid # For generating message_ids

logger = logging.getLogger(__name__)

# --- Message Schema Definition and Validation ---
# This is now more of a guideline for the validation logic, 
# as the structure varies slightly based on the 'role'.

# Common fields and their basic type checks
COMMON_MESSAGE_VALIDATORS = {
    "message_id": lambda x: isinstance(x, str),
    "role": lambda x: isinstance(x, str) and x in ["user", "assistant", "system"],
    "timestamp": lambda x: isinstance(x, str), # Ideally, validate ISO 8601 format
    "request_message_id": lambda x: isinstance(x, str), # Optional, for assistant correlation
}

# Fields required for a message sent TO the LLM (typically role: user or system)
TO_LLM_REQUIRED_FIELDS = ["message_id", "role", "content", "timestamp"]

# Fields required for a message received FROM the LLM (typically role: assistant)
FROM_LLM_REQUIRED_FIELDS = ["message_id", "role", "content", "timestamp"]

class User(models.Model):
    id = fields.BigIntField(pk=True)  # Using BigInt for uint64
    username = fields.CharField(max_length=255, null=False)
    email = fields.CharField(max_length=255, unique=True, null=False)
    password = fields.CharField(max_length=255, null=False)
    is_verified = fields.BooleanField(default=False)
    verification_token = fields.CharField(max_length=10, null=True)
    register_at = fields.DatetimeField(auto_now_add=True)
    # Add a related_name for the reverse relation from User to Course
    # courses: fields.ReverseRelation["Course"] # This will be automatically available

    class Meta:
        table = "users"

class Course(models.Model):
    id = fields.BigIntField(pk=True)
    name = fields.CharField(max_length=255, null=False)
    desc = fields.TextField(null=True) # Description can be optional or longer
    created_at = fields.DatetimeField(auto_now_add=True)
    # Many-to-one relationship: A course belongs to a user
    # 'models.User' refers to the User model in the current app/module context
    # related_name='courses' allows you to access user.courses to get all courses for a user
    owner = fields.ForeignKeyField('models.User', related_name='courses', description="The user who owns/created this course")

    def __str__(self):
        return self.name

    class Meta:
        table = "courses"

class PrincipalChatHistory(models.Model):
    """
    Stores chat history with a principal AI or system.

    The `messages` field is a JSON array. Each object in the array represents a turn.

    Example of a message sent TO the LLM (e.g., by a user):
    {
        "message_id": "usermsg-1234",
        "role": "user",
        "content": "What are the key concepts in quantum computing?", // Plain text
        "timestamp": "2024-05-15T10:00:00Z"
    }

    Example of a message received FROM the LLM (e.g., AI assistant response):
    {
        "message_id": "prinmsg-5678", // Optional, can be generated by your system
        "role": "assistant",
        "content": { // JSON object from the LLM
            "text": "Quantum computing relies on superposition and entanglement...",
            "calls": [
                {
                    "name": "create_course",
                    "args": {
                        "name": "Quantum Computing",
                        "description": "A fundamental theory in physics that describes the behavior of matter and energy at the atomic and subatomic scales, including concepts like wave-particle duality, superposition, and quantum entanglement"
                    }
                },
                {
                    "name": "modify_course",
                    "args": {
                        "name": "Quantum Computing", # Here, we select the course by parameters without new_ prefix
                        "new_description": "A fundamental theory in physics that describes the behavior of matter and energy at the atomic and subatomic scales, including concepts like wave-particle duality, superposition, and quantum entanglement"
                    } # And modify new_ prefixed parameters to the new value.
                },
                {
                    "name": "delete_course",
                    "args": {
                        "name": "Quantum Computing"
                    }
                },
                {
                    "name": "list_courses",
                    "args": {}
                }
            ]
        },
        "request_message_id": "usermsg-1234", // Correlates to the user's message
        "timestamp": "2024-05-15T10:01:00Z"
    }
    """
    id = fields.BigIntField(pk=True)
    
    # Link to the user involved in the chat
    user = fields.ForeignKeyField('models.User', related_name='principal_chat_history',
                                  description="The user engaging in the principal chat")
    
    # Potentially link to a specific course or learning goal if the chat is contextual
    # course = fields.ForeignKeyField('models.Course', related_name='principal_chat_history', null=True, blank=True)
    # learning_goal = fields.ForeignKeyField('models.LearningGoal', related_name='principal_chat_history', null=True, blank=True) # Assuming you have LearningGoal model

    # The chat message itself, stored as JSON
    # A JSONField can store complex structured data like a list of message objects
    messages = fields.JSONField(description="JSON-formatted list of chat message objects", default=list) # Default to empty list
    
    # Timestamp for when this chat entry was created or last updated
    timestamp = fields.DatetimeField(auto_now_add=True) # Or auto_now=True if you want it to update on every save
    
    # Optional: Store metadata about the chat session if a single entry represents a session summary
    session_id = fields.CharField(max_length=255, null=True, blank=True, unique=True, index=True,
                                  description="Optional unique ID for a chat session")
    
    # Optional: Store a summary of the chat, if applicable
    summary = fields.TextField(null=True, blank=True)

    # Optional: Any other relevant data you want to store, perhaps as a JSON blob
    additional_data = fields.JSONField(null=True, blank=True, 
                                       description="Any other relevant structured data")

    def _validate_single_message(self, message: dict) -> bool:
        """
        Validates a single message dictionary against the defined schema.

        This method checks for:
        -   The message being a dictionary.
        -   A valid 'role' (user, assistant, system).
        -   Presence of required fields based on the role.
        -   Correct 'content' type based on the role:
            -   'user'/'system': content must be a string.
            -   'assistant': content must be a dictionary with 'text' (string) 
                             and 'calls' (list) keys.
        -   Valid types for other common fields like 'message_id', 'timestamp',
            and 'request_message_id' using COMMON_MESSAGE_VALIDATORS.

        Args:
            message: The message dictionary to validate.

        Returns:
            True if the message is valid, False otherwise.
            Logs warnings for specific validation failures.
        """
        if not isinstance(message, dict):
            logger.warning(f"Message is not a dictionary: {message}")
            return False

        role = message.get("role")
        if not role or not COMMON_MESSAGE_VALIDATORS["role"](role):
            logger.warning(f"Message missing or invalid 'role': {message}")
            return False

        required_fields = []
        content_valid = True

        if role == "user" or role == "system": # Message TO LLM
            required_fields = TO_LLM_REQUIRED_FIELDS
            if not isinstance(message.get("content"), str):
                logger.warning(f"User/System message 'content' must be a string: {message}")
                content_valid = False
        elif role == "assistant": # Message FROM LLM
            required_fields = FROM_LLM_REQUIRED_FIELDS
            content_data = message.get("content")
            if not isinstance(content_data, dict):
                logger.warning(f"Assistant message 'content' must be a JSON object (dict): {message}")
                content_valid = False
            else:
                # Validate specific structure of assistant's content
                if not isinstance(content_data.get("text"), str):
                    logger.warning(f"Assistant message 'content.text' must be a string: {content_data}")
                    content_valid = False
                if not isinstance(content_data.get("calls"), list):
                    logger.warning(f"Assistant message 'content.calls' must be a list: {content_data}")
                    content_valid = False
                # Optionally, add deeper validation for items within the calls list here in the future
        else:
            logger.warning(f"Unknown message role '{role}': {message}")
            return False # Should not happen if role validation is good
        
        if not content_valid:
            return False

        for field in required_fields:
            if field not in message:
                logger.warning(f"Message (role: {role}) missing required field '{field}': {message}")
                return False
        
        # Validate common fields (excluding content, which is handled above)
        for key, value in message.items():
            if key == "content": 
                continue 
            validator = COMMON_MESSAGE_VALIDATORS.get(key)
            if validator and not validator(value):
                logger.warning(f"Message field '{key}' failed validation (value: {value}): {message}")
                return False
        return True

    def validate_messages_field(self) -> bool:
        """
        Validates the entire 'messages' field of a PrincipalChatHistory instance.

        This method ensures that 'self.messages' is a list and that each
        message object within the list conforms to the structure validated
        by `_validate_single_message`.

        Returns:
            True if the 'messages' field and all its contained messages are valid,
            False otherwise. Logs warnings for failures.
        """
        if not isinstance(self.messages, list):
            logger.warning(f"History ID {self.id}: 'messages' field is not a list.")
            return False
        for i, msg in enumerate(self.messages):
            if not self._validate_single_message(msg):
                logger.warning(f"History ID {self.id}: Invalid message at index {i}.")
                return False
        return True

    # --- Helper to create a user message structure ---
    @staticmethod
    def create_user_message_payload(content: str, message_id: str | None = None) -> dict:
        """
        Creates a structured dictionary for a user message.

        Generates a UUID for `message_id` prefixed with "usermsg-" if not provided.
        Sets the role to "user" and includes the current UTC timestamp.

        Args:
            content: The text content of the user's message.
            message_id: Optional. A specific message ID to use. If None,
                        a new ID will be generated.

        Returns:
            A dictionary representing the user message payload.
        """
        # If message_id is provided, use it; otherwise, generate with prefix.
        # This allows for scenarios where an ID might come from an external source.
        final_message_id = message_id
        if not final_message_id:
            final_message_id = f"usermsg-{uuid.uuid4()}"
        return {
            "message_id": final_message_id,
            "role": "user",
            "content": content,
            "timestamp": datetime.now(timezone.utc).isoformat(timespec='seconds') + "Z"
        }

    # --- Helper to create an assistant message structure ---
    @staticmethod
    def create_assistant_message_payload(text_content: str, calls_content: list | None = None,
                                         request_message_id: str | None = None, 
                                         message_id: str | None = None) -> dict:
        """
        Creates a structured dictionary for an assistant message.

        Generates a UUID for `message_id` prefixed with "prinmsg-" if not provided.
        Sets the role to "assistant". The 'content' is a dictionary containing
        'text' and 'calls'. Includes the current UTC timestamp and an optional
        'request_message_id' to correlate with a user message.

        Args:
            text_content: The main textual response from the assistant.
            calls_content: Optional. A list of call-related dictionaries or an empty list. Defaults to [].
            request_message_id: Optional. The ID of the user message this assistant
                                message is responding to.
            message_id: Optional. A specific message ID to use. If None,
                        a new ID will be generated.

        Returns:
            A dictionary representing the assistant message payload.
        """
        final_message_id = message_id
        if not final_message_id:
            final_message_id = f"prinmsg-{uuid.uuid4()}" # Changed prefix
        
        # Ensure calls_content is a list, defaulting to empty if None
        final_calls_content = calls_content if calls_content is not None else []

        return {
            "message_id": final_message_id,
            "role": "assistant",
            "content": {
                "text": text_content,
                "calls": final_calls_content # Changed from 'courses' to 'calls'
            },
            "request_message_id": request_message_id,
            "timestamp": datetime.now(timezone.utc).isoformat(timespec='seconds') + "Z"
        }

    async def insert_message(self, new_message: dict, use_raw_sql: bool = False) -> bool:
        """
        Inserts a new message into the chat history.

        The message is first validated using `_validate_single_message`.
        It can be inserted either by updating the JSON field directly via the ORM
        or by using a raw SQL JSON_ARRAY_APPEND operation.

        Args:
            new_message: The message dictionary to insert.
            use_raw_sql: If True, uses raw SQL for insertion. Otherwise, uses ORM.
                         Raw SQL can be more efficient for JSON array appends
                         but requires the instance to be already saved (have an ID).

        Returns:
            True if the message was successfully inserted, False otherwise.
            Logs errors or warnings on failure.
        """
        if not self._validate_single_message(new_message):
            logger.error(f"History ID {self.id if self.id else 'New'}: New message failed validation: {new_message}")
            return False
        # ... (rest of insert_message as before, it should work with the new validation) ...
        # Ensure that self.messages is initialized before append if using ORM path
        if not use_raw_sql and not isinstance(self.messages, list):
            self.messages = []

        if use_raw_sql:
            if not self.id:
                logger.error("Cannot use raw SQL to insert message for an unsaved PrincipalChatHistory instance (ID is None).")
                return False
            new_message_json_string = py_json.dumps(new_message)
            async with in_transaction() as conn:
                query = """
                    UPDATE principal_chat_history
                    SET messages = JSON_ARRAY_APPEND(COALESCE(messages, JSON_ARRAY()), '$', CAST(%s AS JSON))
                    WHERE id = %s;
                """
                try:
                    await conn.execute_query(query, [new_message_json_string, self.id])
                    logger.info(f"History ID {self.id}: Appended message via raw SQL.")
                    current_db_instance = await type(self).get(id=self.id)
                    self.messages = current_db_instance.messages
                    return True
                except Exception as e:
                    logger.error(f"History ID {self.id}: Error appending message via raw SQL: {e}")
                    return False
        else:
            if not isinstance(self.messages, list):
                 self.messages = [] 
            self.messages.append(new_message)
            try:
                await self.save(update_fields=['messages'])
                logger.info(f"History ID {self.id if self.id else 'Saved'}: Appended message via ORM.")
                return True
            except Exception as e:
                logger.error(f"History ID {self.id if self.id else 'New'}: Error appending message via ORM: {e}")
                if len(self.messages) > 0 and self.messages[-1] == new_message: # Basic check before pop
                    self.messages.pop()
                return False

    async def delete_message(self, index: int | None = None, use_raw_sql: bool = False) -> bool:
        """
        Deletes a message from the chat history by its index or the last message.

        Can delete using ORM list manipulation or raw SQL JSON_REMOVE.
        If `index` is None or -1, the last message is targeted.

        Args:
            index: The 0-based index of the message to delete.
                   If None or -1, the last message will be deleted.
            use_raw_sql: If True, uses raw SQL for deletion. Otherwise, uses ORM.
                         Raw SQL requires the instance to be saved (have an ID).

        Returns:
            True if a message was successfully deleted, False otherwise.
            Logs errors or warnings on failure or if no message was deleted
            (e.g., index out of bounds, empty list).
        """
        # Ensure the instance is saved if using raw SQL, as ID is needed.
        if not self.id and use_raw_sql:
            logger.error("Cannot use raw SQL to delete message for an unsaved PrincipalChatHistory instance (ID is None).")
            return False
        # (rest of delete_message logic from previous version is generally fine)
        if use_raw_sql:
            path_to_remove = f'$[{index if index is not None and index >= 0 else "last"}]'
            if index is not None and index < -1:
                logger.warning(f"History ID {self.id}: Raw SQL delete for general negative indices (e.g., {index}) not directly supported by simple path, adjust index or logic.")
                return False 
            if index == -1: path_to_remove = '$[last]'
            elif index is None: path_to_remove = '$[last]'
            else: path_to_remove = f'$[{index}]'

            async with in_transaction() as conn:
                query = """
                    UPDATE principal_chat_history
                    SET messages = JSON_REMOVE(messages, %s)
                    WHERE id = %s AND JSON_TYPE(messages) = 'ARRAY' AND JSON_LENGTH(messages) > 0
                """
                if index is not None and index >= 0 :
                    query += f" AND JSON_LENGTH(messages) > {index}"
                query += ";"
                try:
                    result = await conn.execute_query(query, [path_to_remove, self.id])
                    if result[0] > 0: 
                        logger.info(f"History ID {self.id}: Deleted message (path: {path_to_remove}) via raw SQL.")
                        current_db_instance = await type(self).get(id=self.id)
                        self.messages = current_db_instance.messages
                        return True
                    else:
                        logger.warning(f"History ID {self.id}: No message deleted via raw SQL (path: {path_to_remove}). May be empty, non-array, or index out of bounds.")
                        return False
                except Exception as e:
                    logger.error(f"History ID {self.id}: Error deleting message via raw SQL: {e}")
                    return False
        else:
            if not isinstance(self.messages, list) or not self.messages:
                logger.warning(f"History ID {self.id if self.id else 'New'}: No messages to delete (ORM).")
                return False
            actual_index = index
            if index is None or index == -1:
                if not self.messages: return False
                actual_index = len(self.messages) - 1
            if not (0 <= actual_index < len(self.messages)):
                logger.warning(f"History ID {self.id if self.id else 'New'}: Invalid delete index {actual_index} (ORM).")
                return False
            deleted_message = self.messages.pop(actual_index)
            try:
                await self.save(update_fields=['messages'])
                logger.info(f"History ID {self.id if self.id else 'Saved'}: Deleted message at index {actual_index} via ORM. Content summary: {str(deleted_message.get('content', ''))[:30]}...")
                return True
            except Exception as e:
                logger.error(f"History ID {self.id if self.id else 'New'}: Error deleting message via ORM: {e}")
                self.messages.insert(actual_index, deleted_message) 
                return False

    def __str__(self):
        """
        Returns a string representation of the PrincipalChatHistory instance.

        Includes the user ID, instance ID, and timestamp for easy identification.
        """
        return f"Chat history for User ID: {self.user_id} (ID: {self.id}) at {self.timestamp}"

    class Meta:
        table = "principal_chat_history"
        ordering = ["-timestamp"] # Show newest chat histories first by default

def load_db_config():
    """Load database configuration from config.yml"""
    # Get the project root directory (where run.py is located)
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    config_path = os.path.join(project_root, "backend", "config", "config.yml")
    
    with open(config_path, "r") as f:
        config = yaml.safe_load(f)
        return config["database"]

def init_db(app):
    """Initialize database connection for Sanic app"""
    db_config = load_db_config()
    
    # Construct database URL
    db_url = f"mysql://{db_config['user']}:{db_config['password']}@{db_config['host']}:{db_config['port']}/{db_config['name']}"
    
    # Register Tortoise ORM with Sanic
    register_tortoise(
        app,
        db_url=db_url,
        modules={"models": ["ai_engine.db"]},
        generate_schemas=True,  # Auto-generate schemas
    )
