"""
Database models for the principal AI application.

This module contains the database models for managing chat history and user interactions
with the principal AI system.
"""

from tortoise import fields, models
from loguru import logger

class PrincipalChatHistory(models.Model):
    """
    Stores chat history with a principal AI or system.

    The `messages` field is a JSON array. Each object in the array represents a turn.

    Example of a message sent TO the LLM (e.g., by a user):
    {
        "message_id": "usermsg-1234",
        "role": "user",
        "content": "What are the key concepts in quantum computing?", // Plain text
        "timestamp": "2024-05-15T10:00:00Z"
    }

    Example of a message received FROM the LLM (e.g., AI assistant response):
    {
        "message_id": "prinmsg-5678", // Optional, can be generated by your system
        "role": "assistant",
        "content": { // JSON object from the LLM
            "text": "Quantum computing relies on superposition and entanglement...",
            "calls": [
                {
                    "name": "create_course",
                    "args": {
                        "name": "Quantum Computing",
                        "description": "A fundamental theory in physics..."
                    }
                }
            ]
        },
        "request_message_id": "usermsg-1234", // Correlates to the user's message
        "timestamp": "2024-05-15T10:01:00Z"
    }
    """
    # Model fields
    id = fields.BigIntField(pk=True)
    user = fields.ForeignKeyField('models.User', related_name='principal_chat_history',
                                description="The user engaging in the principal chat")
    messages = fields.JSONField(description="JSON-formatted list of chat message objects", default=list)
    added = fields.DatetimeField(auto_now_add=True)

    class Meta:
        table = "principal_chat_history"
        #ordering = ["-timestamp"]  # Show newest chat histories first by default