"""
Utility functions for the principal application.

This module contains helper functions used across the principal application,
particularly for WebSocket communication and message processing.
"""

import ujson as json
import uuid
from typing import Optional, Dict, Any, List
from datetime import datetime
from loguru import logger
from sanic import Websocket
from langchain.schema import BaseMessage
from langchain.callbacks.base import AsyncCallbackHandler
from langchain.schema import LLMResult
from ai_engine.logging import log_exception

from .course import generate_course_outline
from ..ai.llm import LLM
from .chat import PrincipalChat
from .models import Course

class PlaintextWSStreamingCallback(AsyncCallbackHandler):
    """
    Callback handler for streaming LLM responses through WebSocket.
    
    This handler streams token-by-token responses from the LLM to the WebSocket client
    in a standardized JSON format.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        """
        Initialize the callback handler.
        
        Args:
            ws: WebSocket connection to stream to
            session_id: Session ID for logging
        """
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.message_id = str(uuid.uuid4())
        self.collected_tokens = []
        self.token_count = 0
        logger.debug(f"[TRACE] WSStreamingCallback: Initialized with message_id={self.message_id}")
        
    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Handle new token from LLM.
        
        Args:
            token: The new token generated by the LLM
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            self.collected_tokens.append(token)
            self.token_count += 1
            
            # Log every 10 tokens to avoid excessive logging
            if self.token_count <= 5 or self.token_count % 50 == 0:
                logger.debug(f"[TRACE] WSStreamingCallback: Received token #{self.token_count}: '{token[:10]}...' ({len(token)} chars)")
            
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": token,
                "timestamp": datetime.now().isoformat(),
                "is_final": False
            }))
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """
        Handle end of LLM response.
        
        Args:
            response: The final LLM result
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            # Send completion signal
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": "",
                "timestamp": datetime.now().isoformat(),
                "is_final": True
            }))
            
            # Log completion
            full_content = self.get_content()
            logger.debug(f"[TRACE] WSStreamingCallback: Completed with {self.token_count} tokens, total length: {len(full_content)} chars")
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending stream end: {e}")
            
    def get_content(self) -> str:
        """Get the complete collected response."""
        return "".join(self.collected_tokens)
    
class NewWSStreamingCallback(AsyncCallbackHandler):
    """
    Callback handler for streaming LLM responses through WebSocket.
    Streams markdown content until delimiter, then streams JSON metadata.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.message_id = str(uuid.uuid4())
        self.buffer = ""
        self.markdown_content = ""
        self.found_delimiter = False
        self.finalized = False
        logger.debug(f"[TRACE] NewWSStreamingCallback: Initialized with message_id={self.message_id}")

    def __clean_buffer(self) -> str:
        """Clean the buffer for JSON parsing."""
        clean = self.buffer.strip()
        if clean.startswith("---"):
            clean = clean[3:].strip()
        return clean
        
    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Handle new token from LLM."""
        try:
            if not self.found_delimiter:
                if "---" in token:
                    # Split at delimiter
                    markdown, metadata = token.split("---", 1)
                    if markdown:
                        await self.__send_message("markdown", markdown)
                        self.markdown_content += markdown
                    if metadata:
                        self.buffer = metadata.strip()  # Remove any leading/trailing whitespace
                    self.found_delimiter = True
                else:
                    await self.__send_message("markdown", token)
                    self.markdown_content += token
            if self.found_delimiter:
                # After delimiter, just buffer metadata
                self.buffer += token
                # Only try parsing if we see a closing brace
                if "}" in token:
                    await self.__try_parse_metadata()
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            await self.__send_error("Error processing token")

    async def __try_parse_metadata(self) -> None:
        """Try to parse and stream buffered metadata."""
        try:
            metadata = json.loads(self.__clean_buffer())
            await self.__send_message("metadata", metadata)
            self.buffer = ""  # Clear buffer on successful parse
        except json.JSONDecodeError as e:
            if self.finalized:
                logger.error(f"[{self.session_id}] Invalid JSON metadata at stream end: {e}")
                logger.error(f"[{self.session_id}] Buffer content: {self.buffer}")
                await self.__send_error("Invalid JSON metadata received from LLM")

    async def __send_message(self, msg_type: str, content: Any) -> None:
        """Send a message to the WebSocket client."""
        if msg_type == "markdown":
            await self.ws.send(content)
            return
        
        await self.ws.send(json.dumps({
            "type": msg_type,
            "message_id": self.message_id,
            "content": content,
            "timestamp": datetime.now().isoformat()
        }))

    async def __send_error(self, error: str) -> None:
        """Send an error message to the WebSocket client."""
        await self.__send_message("error", {
            "message": error,
            "session_id": self.session_id
        })

    def get_content(self) -> str:
        """Get the complete markdown content for chat history."""
        return self.markdown_content
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """Handle end of LLM response."""
        try:
            self.finalized = True
            # Try to parse any remaining buffered metadata
            if self.buffer:
                await self.__try_parse_metadata()
            
            # Send completion signal
            await self.__send_message("complete", None)
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error in stream end: {e}")
            await self.__send_error("Error at stream end")

async def send_ws_error(ws: Websocket, error: str, status_code: int = 400) -> None:
    """
    Send an error message to the WebSocket client.
    
    Args:
        ws: WebSocket connection
        error: Error message to send
        status_code: HTTP status code to include in the error
    """
    await ws.send(json.dumps({
        "type": "error",
        "error": error,
        "status_code": status_code,
        "timestamp": datetime.now().isoformat()
    }))

async def handle_user_message(ws: Websocket, chat: PrincipalChat, llm: LLM, content: str, session_id: str) -> None:
    """
    Process a user message from a WebSocket client.
    
    This function handles the complete message processing pipeline:
    1. Saves the user message to chat history
    2. Gets chat history as LangChain messages
    3. Generates a streaming response using the LLM
    4. Saves the complete AI response to chat history
    
    Args:
        ws: WebSocket connection
        chat: PrincipalChat instance to use
        llm: LLM instance for generating responses
        content: Message content
        session_id: WebSocket session ID for logging
        
    Raises:
        ConnectionError: If the WebSocket connection is closed
        Exception: For any other errors during processing
    """
    try:
        logger.info(f"[{session_id}] Processing message")
        
        # Save user message to chat history
        await chat.add_message(content, "user")
        
        # Create streaming callback
        callback = NewWSStreamingCallback(ws, session_id)
        
        # Get messages and generate streaming response using the LLM class
        messages = chat.langchain_messages
        response = await llm.agenerate_response(messages, callbacks=[callback])
        
        # Save complete AI response to chat history
        await chat.add_message(callback.get_content(), "assistant")
        
    except ConnectionError as e:
        logger.info(f"[{session_id}] WebSocket closed during streaming: {str(e)}")
    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing message")
        try:
            await send_ws_error(ws, f"Error processing message: {str(e)}", 500)
        except:
            pass 

async def handle_course_req(ws: Websocket, content: str, session_id: str) -> None:
    """
    Process a course request from a WebSocket client.
    """
    try:
        logger.info(f"[{session_id}] Processing course request")
        
        if content["type"] == "create":
            course = await Course.create(
                name=content["name"],
                description=content["description"]
            )
            await course.save()
            # Pre-send successful message to avoid waiting for outline generation
            await ws.send(format_json_course_response("create_course", course))
            outline = await generate_course_outline(course.id)
            course.outline = outline
            await course.save()
            await ws.send(format_json_course_response("course_outline", course))
        
        elif content["type"] == "delete":
            course = await Course.get(id=content["course_id"])
            await course.delete()
            await ws.send(format_json_course_response("delete_course", None))

        elif content["type"] == "update":
            course = await Course.get(id=content["course_id"])
            await course.save()
            await ws.send(format_json_course_response("update_course", course))
        else:
            logger.info(f"[{session_id}] Unexpected course request type: {content['type']}")
            await send_ws_error(ws, f"Unexpected course request type: {content['type']}", 400)

    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing course request")
        try:
            await send_ws_error(ws, f"Error processing course request: {str(e)}", 500)
        except:
            pass

    
def format_json_course_response(msgtype: str, course: Optional[Course] = None) -> dict:
    """
    Format a course response for the WebSocket client.
    """
    if msgtype == "delete_course" and course is None:
        return json.dumps({
            "type": msgtype,
            "success": True
        })
    return json.dumps({
        "type": msgtype,
        "course_id": course.id,
        "name": course.name,
        "description": course.description,
        "outline": course.outline if course.outline else "Generating..."
    })
