"""
Utility functions for the principal application.

This module contains helper functions used across the principal application,
particularly for WebSocket communication and message processing.
"""

import ujson as json
import uuid
from typing import Optional, Dict, Any, List
from datetime import datetime
from loguru import logger
from sanic import Websocket
from langchain.schema import BaseMessage
from langchain.callbacks.base import AsyncCallbackHandler
from langchain.schema import LLMResult
from ai_engine.logging import log_exception

from .course import generate_course_outline
from ..ai.llm import LLM
from .chat import PrincipalChat
from ..course.models import Course

class LegacyWSStreamingCallback(AsyncCallbackHandler):
    """
    Legacy callback handler for streaming LLM responses through WebSocket.
    This implementation is deprecated in favor of NewWSStreamingCallback.
    
    This handler streams token-by-token responses from the LLM to the WebSocket client
    in a standardized JSON format with full metadata for each token.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        """
        Initialize the callback handler.
        
        Args:
            ws: WebSocket connection to stream to
            session_id: Session ID for logging
        """
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.message_id = str(uuid.uuid4())
        self.collected_tokens = []
        self.token_count = 0
        logger.debug(f"[TRACE] WSStreamingCallback: Initialized with message_id={self.message_id}")
        
    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Handle new token from LLM.
        
        Args:
            token: The new token generated by the LLM
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            self.collected_tokens.append(token)
            self.token_count += 1
            
            # Log every 10 tokens to avoid excessive logging
            if self.token_count <= 5 or self.token_count % 50 == 0:
                logger.debug(f"[TRACE] WSStreamingCallback: Received token #{self.token_count}: '{token[:10]}...' ({len(token)} chars)")
            
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": token,
                "timestamp": datetime.now().isoformat(),
                "is_final": False
            }))
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """
        Handle end of LLM response.
        
        Args:
            response: The final LLM result
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            # Send completion signal
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": "",
                "timestamp": datetime.now().isoformat(),
                "is_final": True
            }))
            
            # Log completion
            full_content = self.get_content()
            logger.debug(f"[TRACE] WSStreamingCallback: Completed with {self.token_count} tokens, total length: {len(full_content)} chars")
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending stream end: {e}")
            
    def get_content(self) -> str:
        """Get the complete collected response."""
        return "".join(self.collected_tokens)
    
class NewWSStreamingCallback(AsyncCallbackHandler):
    """
    Callback handler for streaming LLM responses through WebSocket.
    Streams markdown content until delimiter, then streams JSON metadata.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.message_id = str(uuid.uuid4())
        self.buffer = ""
        self.markdown_content = ""
        self.found_delimiter = False
        self.finalized = False
        self.started = False
        logger.debug(f"[TRACE] NewWSStreamingCallback: Initialized with message_id={self.message_id}")

    def __clean_buffer(self) -> str:
        """Clean the buffer for JSON parsing."""
        clean = self.buffer.strip()
        if clean.startswith("---"):
            clean = clean[3:].strip()
        return clean
        
    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Handle new token from LLM."""
        if not self.started:
            self.started = True
            start_msg = json.dumps({
                "type": "start",
                "message_id": self.message_id,
                "content": None,
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Sending start message: {repr(start_msg)}")
            await self.ws.send(start_msg)
            
        try:
            if not self.found_delimiter:
                if "---" in token:
                    # Split at delimiter
                    markdown, metadata = token.split("---", 1)
                    if markdown:
                        logger.debug(f"[{self.session_id}] Sending markdown: {repr(markdown)}")
                        await self.ws.send(markdown)
                        self.markdown_content += markdown
                    if metadata:
                        self.buffer = metadata.strip()
                    self.found_delimiter = True
                else:
                    logger.debug(f"[{self.session_id}] Sending markdown: {repr(token)}")
                    await self.ws.send(token)
                    self.markdown_content += token
            if self.found_delimiter:
                # After delimiter, just buffer metadata
                self.buffer += token
                # Only try parsing if we see a closing brace
                if "}" in token:
                    try:
                        metadata = json.loads(self.__clean_buffer())
                        metadata_msg = json.dumps({
                            "type": "metadata",
                            "message_id": self.message_id,
                            "content": metadata,
                            "timestamp": datetime.now().isoformat()
                        })
                        logger.debug(f"[{self.session_id}] Sending metadata: {repr(metadata_msg)}")
                        await self.ws.send(metadata_msg)
                        self.buffer = ""
                    except json.JSONDecodeError as e:
                        if self.finalized:
                            logger.error(f"[{self.session_id}] Invalid JSON metadata at stream end: {e}")
                            logger.error(f"[{self.session_id}] Buffer content: {self.buffer}")
                            error_msg = json.dumps({
                                "type": "error",
                                "message_id": self.message_id,
                                "content": {
                                    "message": "Invalid JSON metadata received from LLM",
                                    "session_id": self.session_id
                                },
                                "timestamp": datetime.now().isoformat()
                            })
                            logger.debug(f"[{self.session_id}] Sending error: {repr(error_msg)}")
                            await self.ws.send(error_msg)
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            error_msg = json.dumps({
                "type": "error",
                "message_id": self.message_id,
                "content": {
                    "message": "Error processing token",
                    "session_id": self.session_id
                },
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Sending error: {repr(error_msg)}")
            await self.ws.send(error_msg)

    def get_content(self) -> str:
        """Get the complete markdown content for chat history."""
        return self.markdown_content
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """Handle end of LLM response."""
        try:
            self.finalized = True
            # Try to parse any remaining buffered metadata
            if self.buffer:
                try:
                    metadata = json.loads(self.__clean_buffer())
                    metadata_msg = json.dumps({
                        "type": "metadata",
                        "message_id": self.message_id,
                        "content": metadata,
                        "timestamp": datetime.now().isoformat()
                    })
                    logger.debug(f"[{self.session_id}] Sending final metadata: {repr(metadata_msg)}")
                    await self.ws.send(metadata_msg)
                except json.JSONDecodeError as e:
                    logger.error(f"[{self.session_id}] Invalid JSON metadata at stream end: {e}")
                    logger.error(f"[{self.session_id}] Buffer content: {self.buffer}")
                    error_msg = json.dumps({
                        "type": "error",
                        "message_id": self.message_id,
                        "content": {
                            "message": "Invalid JSON metadata received from LLM",
                            "session_id": self.session_id
                        },
                        "timestamp": datetime.now().isoformat()
                    })
                    logger.debug(f"[{self.session_id}] Sending error: {repr(error_msg)}")
                    await self.ws.send(error_msg)
            
            # Send completion signal
            complete_msg = json.dumps({
                "type": "complete",
                "message_id": self.message_id,
                "content": None,
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Sending complete: {repr(complete_msg)}")
            await self.ws.send(complete_msg)
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error in stream end: {e}")
            error_msg = json.dumps({
                "type": "error",
                "message_id": self.message_id,
                "content": {
                    "message": "Error at stream end",
                    "session_id": self.session_id
                },
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Sending error: {repr(error_msg)}")
            await self.ws.send(error_msg)

async def send_ws_error(ws: Websocket, error: str, status_code: int = 400) -> None:
    """
    Send an error message to the WebSocket client.
    
    Args:
        ws: WebSocket connection
        error: Error message to send
        status_code: HTTP status code to include in the error
    """
    await ws.send(json.dumps({
        "type": "error",
        "error": error,
        "status_code": status_code,
        "timestamp": datetime.now().isoformat()
    }))

async def handle_user_message(ws: Websocket, chat: PrincipalChat, llm: LLM, content: str, session_id: str) -> None:
    """
    Process a user message from a WebSocket client.
    
    This function handles the complete message processing pipeline:
    1. Saves the user message to chat history
    2. Gets chat history as LangChain messages
    3. Generates a streaming response using the LLM
    4. Saves the complete AI response to chat history
    
    Args:
        ws: WebSocket connection
        chat: PrincipalChat instance to use
        llm: LLM instance for generating responses
        content: Message content
        session_id: WebSocket session ID for logging
        
    Raises:
        ConnectionError: If the WebSocket connection is closed
        Exception: For any other errors during processing
    """
    try:
        logger.info(f"[{session_id}] Processing message")
        
        # Save user message to chat history
        await chat.add_message(content, "user")
        
        # Create streaming callback
        callback = NewWSStreamingCallback(ws, session_id)
        
        # Get messages and generate streaming response using the LLM class
        messages = chat.langchain_messages
        response = await llm.agenerate_response(messages, callbacks=[callback])
        
        # Save complete AI response to chat history
        await chat.add_message(callback.get_content(), "assistant")
        
    except ConnectionError as e:
        logger.info(f"[{session_id}] WebSocket closed during streaming: {str(e)}")
    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing message")
        try:
            await send_ws_error(ws, f"Error processing message: {str(e)}", 500)
        except:
            pass 

async def handle_course_req(ws: Websocket, content: str, session_id: str, llm: LLM) -> None:
    """
    Process a course request from a WebSocket client.
    """
    try:
        logger.info(f"[{session_id}] Processing course request")
        
        if content["type"] == "create":
            course = await Course.create(
                name=content["name"],
                description=content["description"]
            )
            await course.save()
            # Pre-send successful message to avoid waiting for outline generation
            await ws.send(format_json_course_response("create_course", course))
            outline = await generate_course_outline(course.id, llm)
            course.outline = outline
            await course.save()
            await ws.send(format_json_course_response("course_outline", course))
        
        elif content["type"] == "delete":
            course = await Course.get(id=content["course_id"])
            await course.delete()
            await ws.send(format_json_course_response("delete_course", None))

        elif content["type"] == "update":
            course = await Course.get(id=content["course_id"])
            await course.save()
            await ws.send(format_json_course_response("update_course", course))
        else:
            logger.info(f"[{session_id}] Unexpected course request type: {content['type']}")
            await send_ws_error(ws, f"Unexpected course request type: {content['type']}", 400)

    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing course request")
        try:
            await send_ws_error(ws, f"Error processing course request: {str(e)}", 500)
        except:
            pass

    
def format_json_course_response(msgtype: str, course: Optional[Course] = None) -> dict:
    """
    Format a course response for the WebSocket client.
    """
    if msgtype == "delete_course" and course is None:
        return json.dumps({
            "type": msgtype,
            "success": True
        })
    return json.dumps({
        "type": msgtype,
        "course_id": course.id,
        "name": course.name,
        "description": course.description,
        "outline": course.outline if course.outline else "Generating..."
    })
