"""
Utility functions for the principal application.

This module contains helper functions used across the principal application,
particularly for WebSocket communication and message processing.
"""

import ujson as json
import uuid
from typing import Optional, Dict, Any, List
from datetime import datetime
from loguru import logger
from sanic import Websocket
from langchain.schema import BaseMessage
from langchain.callbacks.base import AsyncCallbackHandler
from langchain.schema import LLMResult
from ai_engine.logging import log_exception

from .course import generate_course_outline
from ..ai.llm import LLM
from .chat import PrincipalChat
from ..course.models import Course
from .ai_tools import (
    CreateCourseTool, 
    GetCourseTool, 
    ListCoursesTool, 
    UpdateCourseTool, 
    DeleteCourseTool
)
from ..auth.models import User

class LegacyWSStreamingCallback(AsyncCallbackHandler):
    """
    Legacy callback handler for streaming LLM responses through WebSocket.
    This implementation is deprecated in favor of NewWSStreamingCallback.
    
    This handler streams token-by-token responses from the LLM to the WebSocket client
    in a standardized JSON format with full metadata for each token.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        """
        Initialize the callback handler.
        
        Args:
            ws: WebSocket connection to stream to
            session_id: Session ID for logging
        """
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.message_id = str(uuid.uuid4())
        self.collected_tokens = []
        self.token_count = 0
        logger.debug(f"[TRACE] WSStreamingCallback: Initialized with message_id={self.message_id}")
        
    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """
        Handle new token from LLM.
        
        Args:
            token: The new token generated by the LLM
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            self.collected_tokens.append(token)
            self.token_count += 1
            
            # Log every 10 tokens to avoid excessive logging
            if self.token_count <= 5 or self.token_count % 50 == 0:
                logger.debug(f"[TRACE] WSStreamingCallback: Received token #{self.token_count}: '{token[:10]}...' ({len(token)} chars)")
            
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": token,
                "timestamp": datetime.now().isoformat(),
                "is_final": False
            }))
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """
        Handle end of LLM response.
        
        Args:
            response: The final LLM result
            **kwargs: Additional arguments passed by LangChain
        """
        try:
            # Send completion signal
            await self.ws.send(json.dumps({
                "type": "token",
                "message_id": self.message_id,
                "content": "",
                "timestamp": datetime.now().isoformat(),
                "is_final": True
            }))
            
            # Log completion
            full_content = self.get_content()
            logger.debug(f"[TRACE] WSStreamingCallback: Completed with {self.token_count} tokens, total length: {len(full_content)} chars")
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending stream end: {e}")
            
    def get_content(self) -> str:
        """Get the complete collected response."""
        return "".join(self.collected_tokens)
    
class SimpleWSStreamingCallback(AsyncCallbackHandler):
    """
    Simple callback handler for streaming LLM responses through WebSocket.
    Sends only plaintext content - no JSON messages, timestamps, or special events.
    """
    
    def __init__(self, ws: Websocket, session_id: str):
        super().__init__()
        self.ws = ws
        self.session_id = session_id
        self.content = ""
        self.message_id = str(uuid.uuid4())  # Add message_id for compatibility
        logger.debug(f"[{self.session_id}] SimpleWSStreamingCallback initialized with message_id={self.message_id}")

    async def on_llm_new_token(self, token: str, **kwargs) -> None:
        """Handle new token from LLM - send raw content."""
        try:
            # Skip empty tokens
            if not token or token.strip() == "":
                return
                
            logger.debug(f"[{self.session_id}] Sending token: {repr(token)}")
            # Send raw content directly
            await self.ws.send(token)
            self.content += token
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error streaming token: {e}")
            await send_ws_error(self.ws, f"Error processing token: {str(e)}", 500)

    async def on_tool_start(self, serialized: Dict[str, Any], input_str: str, **kwargs) -> None:
        """Handle start of tool execution."""
        try:
            tool_name = serialized.get("name", "unknown_tool")
            tool_msg = json.dumps({
                "type": "tool_call_start",
                "tool_call": {
                    "name": tool_name,
                    "status": "running",
                    "parameters": {"input": input_str}
                },
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Tool started: {tool_name}")
            await self.ws.send(tool_msg)
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending tool start: {e}")

    async def on_tool_end(self, output: str, **kwargs) -> None:
        """Handle end of tool execution."""
        try:
            tool_msg = json.dumps({
                "type": "tool_call_update",
                "tool_call": {
                    "status": "success",
                    "result": output
                },
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Tool completed successfully")
            await self.ws.send(tool_msg)
            
            # Check if this is a course-related tool and send course updates
            await self._send_course_updates()
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending tool end: {e}")

    async def on_tool_error(self, error: Exception, **kwargs) -> None:
        """Handle tool execution error."""
        try:
            tool_msg = json.dumps({
                "type": "tool_call_update",
                "tool_call": {
                    "status": "error",
                    "result": str(error)
                },
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Tool error: {str(error)}")
            await self.ws.send(tool_msg)
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending tool error: {e}")

    async def _send_course_updates(self):
        """Send updated course list to frontend."""
        try:
            # Get all courses for the blackboard display
            courses = await Course.all()
            course_data = []
            for course in courses:
                course_data.append({
                    "id": str(course.id),
                    "title": course.name,
                    "description": course.description,
                    "grade_level": getattr(course, 'grade_level', 'Not specified'),
                    "duration": getattr(course, 'duration', 'Not specified'),
                    "format": getattr(course, 'format', 'Not specified')
                })
            
            course_update_msg = json.dumps({
                "type": "course_update",
                "metadata": {
                    "courses": course_data
                },
                "timestamp": datetime.now().isoformat()
            })
            await self.ws.send(course_update_msg)
        except Exception as e:
            logger.error(f"[{self.session_id}] Error sending course updates: {e}")

    def get_content(self) -> str:
        """Get the complete content for chat history."""
        return self.content
            
    async def on_llm_end(self, response: LLMResult, **kwargs) -> None:
        """Handle end of LLM response."""
        try:
            self.finalized = True
            
            # Send completion signal
            complete_msg = json.dumps({
                "type": "response_end",
                "message_id": self.message_id,
                "timestamp": datetime.now().isoformat()
            })
            logger.debug(f"[{self.session_id}] Sending completion message: {complete_msg}")
            await self.ws.send(complete_msg)
            
        except Exception as e:
            logger.error(f"[{self.session_id}] Error in stream end: {e}")
            await send_ws_error(self.ws, f"Error at stream end: {str(e)}", 500)

async def send_ws_error(ws: Websocket, error: str, status_code: int = 400) -> None:
    """
    Send an error message to the WebSocket client.
    
    Args:
        ws: WebSocket connection
        error: Error message to send
        status_code: HTTP status code to include in the error
    """
    await ws.send(json.dumps({
        "type": "error",
        "error": error,
        "status_code": status_code,
        "timestamp": datetime.now().isoformat()
    }))

async def handle_user_message(ws: Websocket, chat: PrincipalChat, llm: LLM, content: str, session_id: str, user_id: Optional[str] = None) -> None:
    """
    Process a user message from a WebSocket client with tool support.
    
    This function handles the complete message processing pipeline:
    1. Saves the user message to chat history
    2. Generates a streaming response using the pre-configured LLM with tools
    3. Saves the complete AI response to chat history
    
    Args:
        ws: WebSocket connection
        chat: PrincipalChat instance to use
        llm: LLM instance for generating responses (already configured with tools)
        content: Message content
        session_id: WebSocket session ID for logging
        user_id: User ID (optional, mainly for backwards compatibility)
        
    Raises:
        ConnectionError: If the WebSocket connection is closed
        Exception: For any other errors during processing
    """
    try:
        logger.info(f"[{session_id}] Processing message with tool support")
        
        # Save user message to chat history
        await chat.add_message(content, "user")
        
        # Create streaming callback
        callback = SimpleWSStreamingCallback(ws, session_id)
        
        # Note: LLM tools are already configured in routes.py during session setup
        logger.debug(f"[{session_id}] Using LLM with {len(llm.tools)} pre-configured tools")
        
        # Get messages and generate streaming response using the LLM class
        messages = chat.langchain_messages
        response = await llm.agenerate_response(messages, callbacks=[callback], use_tools=True)
        
        # Save complete AI response to chat history
        await chat.add_message(callback.get_content(), "assistant")
        
    except ConnectionError as e:
        logger.info(f"[{session_id}] WebSocket closed during streaming: {str(e)}")
    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing message")
        try:
            await send_ws_error(ws, f"Error processing message: {str(e)}", 500)
        except:
            pass

async def handle_course_req(ws: Websocket, content: str, session_id: str, llm: LLM) -> None:
    """
    Process a course request from a WebSocket client.
    """
    try:
        logger.info(f"[{session_id}] Processing course request")
        
        if content["type"] == "create":
            course = await Course.create(
                name=content["name"],
                description=content["description"]
            )
            await course.save()
            # Pre-send successful message to avoid waiting for outline generation
            await ws.send(format_json_course_response("create_course", course))
            outline = await generate_course_outline(course.id, llm)
            course.outline = outline
            await course.save()
            await ws.send(format_json_course_response("course_outline", course))
        
        elif content["type"] == "delete":
            course = await Course.get(id=content["course_id"])
            await course.delete()
            await ws.send(format_json_course_response("delete_course", None))

        elif content["type"] == "update":
            course = await Course.get(id=content["course_id"])
            await course.save()
            await ws.send(format_json_course_response("update_course", course))
        else:
            logger.info(f"[{session_id}] Unexpected course request type: {content['type']}")
            await send_ws_error(ws, f"Unexpected course request type: {content['type']}", 400)

    except Exception as e:
        log_exception(e, f"[{session_id}] Error processing course request")
        try:
            await send_ws_error(ws, f"Error processing course request: {str(e)}", 500)
        except:
            pass

    
def format_json_course_response(msgtype: str, course: Optional[Course] = None) -> dict:
    """
    Format a course response for the WebSocket client.
    """
    if msgtype == "delete_course" and course is None:
        return json.dumps({
            "type": msgtype,
            "success": True
        })
    return json.dumps({
        "type": msgtype,
        "course_id": course.id,
        "name": course.name,
        "description": course.description,
        "outline": course.outline if course.outline else "Generating..."
    })
